version: "3.4"
services:
    pongserver:
        build:
            context: .
            dockerfile: ./PongServer/Dockerfile
        network_mode: host
        expose:
            - "5000"
        ports: 
            - "0.0.0.0:5000:5000"
        volumes: 
            - "./PongServer:/PongGame"
            - "./Thrift:/Thrift"
    pongclient:
        build:
            context: .
            dockerfile: ./PongClient/Dockerfile
        network_mode: host
        volumes: 
            - "./PongClient:/PongGame"
            - "./Thrift:/Thrift"
        stdin_open: true
        tty: true